### ISSUE TITLE
Suggestion/inquiry 

### ISSUE THREAD

**Issue by Kraaven** [satchelfrost/revolvr#44]
Since this game engine is made from the ground up with VR in mind, will it include a lot of the VR important custom components like:
Sockets, direct controller input system, raycasts (for controller), default locomotion presets, default scene presets with headset and controllers set up. etc?

**Comment by satchelfrost** [comment]
Good questions:

- A Raycast component: yeah... I need to get on that. I haven't had the need, but that's something that should be added at some point. I also need to add a quad component so when the raycast hits something I can draw a little dot. If you would like to add a new Raycast component that is of type collider, I wouldn't mind taking a pull request on that (we can correspond more if you're interested).
- Sockets (and/or other networking utilities): not currently a priority. To me, this is something that is very game-dependent. Sure, every strong general purpose game engine will have this, but RevolVR is far from that. I don't see this as being super difficult to add (there are plenty of C/C++ socket libraries), but at the same time it's not high priority.
- I'm not sure what you mean by "direct controller input system". Currently, the meta quest controllers work and are the default OpenXR input profile when using controllers. Hand tracking data is also there, but once again it's quest-specific for now.
- Default locomotion: yes/no. Currently movement is possible already, I have a scene that does simple movement. If you're talking about the typical arc-coming-out-of-controller-onto-floor, then no, that is not built into the engine directly. Once again not every game will use that, but that might be a fun thing to add, perhaps an ArcMovement component.
- Default presets with headset and controllers set up: yes. See the examples in the sample project. For now, loading different scenes is a little jank, you have to comment/uncomment the scene to be loaded in app.cpp.
