### ISSUE TITLE
YouTube and Discord issues

### ISSUE THREAD

**Issue by SliceArtEngine** [satchelfrost/revolvr#47]
Hey Satchel, what happened to your YouTube channel and Discord server?

Btw, Merry Christmas!

**Comment by satchelfrost** [comment]
Thanks, you as well! Yeah sorry, I just decided to quit the YouTube thing. Feel free to DM me on discord though.

**Comment by SliceArtEngine** [comment]
@satchelfrost I'm not able to DM on Discord since your server is down and I don't have your username. Could you send me a PM please? I would love to stay in touch. My Discord username is sliceartengine.
