### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SliceArtEngine** [satchelfrost/revolvr#51]
This native development sample is so much better than what Meta provides! I love that the project provides samples for textures, models, and lighting! I'm a computational geometry developer who specializes in sword collisions. I recently tried your project as I am moving towards implementing my algorithms to work with Vulkan.

I love the work you do for native development and Quest. Can we connect somehow please? My website, TikTok, email (Gmail), and Discord are the same as my GitHub username.

I think we have lots of complimentary skills and I think maybe in the future we can make cool things together.

**Comment by satchelfrost** [comment]
Cool I'm glad you found it useful. I will reach out to you!
